# Site Configuration
# Edit this file to update global site settings

site:
  title: "StyleCare"
  tagline: "Clean girl styling for college women"
  description: "StyleCare helps college women (18-25) build effortless wardrobes with curated clean girl capsules, budget-friendly shopping, and educational styling guides."
  url: "https://stylecare.example.com"
  author: "StyleCare"
  language: "en"
  
  # Contact Information
  phone: "+1 (555) 555-5555"
  phone_raw: "+15555555555"
  email: "hello@stylecare.example.com"
  whatsapp: "15555555555"
  
  # Location (optional)
  location:
    city: "Remote"
    region: "Global"
    coordinates:
      latitude: 0.0
      longitude: 0.0
  
  # Social Media (set real URLs or leave empty to hide)
  social:
    facebook: ""
    instagram: ""
    tiktok: ""
    twitter: ""
  
  # SEO Keywords
  keywords:
    - "clean girl aesthetic"
    - "college styling"
    - "capsule wardrobe"
    - "affordable styling"
    - "style quiz"
    - "student fashion"

# Build Configuration
build:
  output_dir: "docs"
  static_dir: "static"
  template_dir: "templates"
  
# Feature Flags
features:
  show_blog: false
  show_testimonials: true
  show_whatsapp_float: true
  show_pricing: true
  enable_analytics: false
